--liquibase formatted sql

--changeset Jordenn:add-dates-to-radial-analysis
ALTER TABLE radial_analysis
    ADD COLUMN IF NOT EXISTS input_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS end_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
