<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SaxsSpot.NanoSystemService.Contracts\SaxsSpot.NanoSystemService.Contracts.csproj" />
        <ProjectReference Include="..\SaxsSpot.NanoSystemService.Entities\SaxsSpot.NanoSystemService.Entities.csproj" />
        <ProjectReference Include="..\SaxsSpot.NanoSystemService.Storage\SaxsSpot.NanoSystemService.Storage.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SaxsSpot.NanoSystemGeneration.Contracts" Version="1.3.6" />
        <PackageReference Include="SaxsSpot.NanoSystemGeneration.Engine" Version="1.3.6" />
        <PackageReference Include="SaxsSpot.Transport.Contracts" Version="1.0.33" />
        <PackageReference Include="SaxsSpot.Transport.MessageChannel.Contracts" Version="1.0.33" />
    </ItemGroup>

</Project>
