<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SaxsSpot.NanoSystemService.Contracts\SaxsSpot.NanoSystemService.Contracts.csproj" />
        <ProjectReference Include="..\SaxsSpot.NanoSystemService.Domain\SaxsSpot.NanoSystemService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.0.0" />
        <PackageReference Include="FluentResults" Version="4.0.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
        <PackageReference Include="Gridify" Version="2.16.3" />
        <PackageReference Include="MediatR" Version="13.0.0" />
        <PackageReference Include="SaxsSpot.NanoSystemGeneration.Contracts" Version="2.1.0" />
        <PackageReference Include="SaxsSpot.NanoSystemGeneration.Engine" Version="2.1.0" />
        <PackageReference Include="SaxsSpot.Shared.Contracts" Version="1.2.1" />
        <PackageReference Include="SaxsSpot.Shared.ProgressTrackerClient" Version="1.2.1" />
        <PackageReference Include="SaxsSpot.Transport.Contracts" Version="1.0.33" />
        <PackageReference Include="SaxsSpot.Transport.MessageChannel.Contracts" Version="1.0.33" />
    </ItemGroup>

</Project>
