<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuildDate>$([System.DateTime]::Now.ToString('yyyyMMdd'))</BuildDate>
    <BuildTime>$([System.DateTime]::Now.ToString('HHmmss'))</BuildTime>
    <Version>1.0.4+$(BuildDate)$(BuildTime)</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SaxsSpot.NanoSystemService.Application\SaxsSpot.NanoSystemService.Application.csproj" />
    <ProjectReference Include="..\SaxsSpot.NanoSystemService.Domain\SaxsSpot.NanoSystemService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Gridify.EntityFramework" Version="2.16.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="SaxsSpot.Core.CommonObjectStorage" Version="1.0.21" />
    <PackageReference Include="SaxsSpot.Core.Contracts" Version="1.0.21" />
    <PackageReference Include="SaxsSpot.Core.GenericStorage" Version="1.0.21" />
  </ItemGroup>
</Project>