<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="SaxsSpot.Core.Contracts">
        <HintPath>..\..\SaxsSpot.NanoSystemGenerationService\SaxsSpot.NanoSystemGenerationService.Contracts\bin\Debug\net9.0\SaxsSpot.NanoSystemGenerationService.Contracts.dll</HintPath>
      </Reference>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="SaxsSpot.NanoSystemGeneration.Contracts" Version="2.0.3" />
    </ItemGroup>
</Project>
