<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="13.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
        <PackageReference Include="SaxsSpot.Shared.Authenticator" Version="1.0.5" />
        <PackageReference Include="SaxsSpot.Shared.ProgressTrackerClient" Version="1.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SaxsSpot.NanoSystemService.Application\SaxsSpot.NanoSystemService.Application.csproj" />
      <ProjectReference Include="..\SaxsSpot.NanoSystemService.Contracts\SaxsSpot.NanoSystemService.Contracts.csproj" />
      <ProjectReference Include="..\SaxsSpot.NanoSystemService.Storage\SaxsSpot.NanoSystemService.Storage.csproj" />
    </ItemGroup>

</Project>
